### ISSUE TITLE
1.0 Alpha Feature Milestones

### ISSUE THREAD

**Issue by RogerLevy** [RogerLevy/lantern#1]
- [ ] Depth sorting extension
- [ ] Global collision extension
- [ ] Test multitasking extension
- [ ] HP extension
- [ ] Background music streaming
- [ ] Tilemap system with collision detection
- [ ] Tiled support (including tilemaps)
