### ISSUE TITLE
1.0 milestones

### ISSUE THREAD

**Issue by RogerLevy** [RogerLevy/lantern#10]
- [ ] Global collision extension
- [ ] Intersections module (part of Bubble probably)
- [ ] Simple dialog tree module
- [ ] GUI system
- [ ] Sort out issues related to Idioms
