### ISSUE TITLE
0.9 milestones

### ISSUE THREAD

**Issue by RogerLevy** [RogerLevy/lantern#11]
Milestones:

- [ ] Release exporter
- [x] Depth sorting extension (new top-down perspective example)
- [x] Tilemap system with collision detection 
- [x] Background music streaming 
- [x] Test multitasking extension
- [x] Partial Tiled support (objects, rectangles, tilemaps)
- [x] FMOD version of audio system (Allegro's audio API is awful!)
