### ISSUE TITLE
1.1 Milestones

### ISSUE THREAD

**Issue by RogerLevy** [RogerLevy/lantern#2]
Some may be moved to 1.2

- [ ] Advanced sound engine (pitch, pan, volume, ramps, software streams, DSP support, audio input)
- [ ] Mappable input
- [ ] Shader support
- [ ] Parenting
- [ ] Adaptive resolution

Added 6/23:

- [ ] Graphics & animation editor
- [ ] World/Tileset/Tilemap editor
- [ ] SFX editor
- [ ] Complete Workspaces integration
